### ISSUE TITLE
Error while running hi-patch_v1.m

### ISSUE THREAD

**Issue by Surabhi-CSB** [hector-s-m/hi-patch#1]
Hi,

I am getting the following error while running the hi-patch script:

Unrecognized field name "at_name".

Error in hi_patch_v1 (line 586)
lyscount = sum(count(surfdata.at_name(:,1),'NZ')); % count number of lysine primary NH2s

Can you help to resolve this?

**Comment by hector-s-m** [comment]
Sure thing. Would you mind sharing your crystal structure? Either PDB ID, or if you'd rather send me your structure via email (hector.sanchez-moran@colorado.edu) that would work too.

**Comment by hector-s-m** [comment]
> Hi,
> 
> I am getting the following error while running the hi-patch script:
> 
> Unrecognized field name "at_name".
> 
> Error in hi_patch_v1 (line 586) lyscount = sum(count(surfdata.at_name(:,1),'NZ')); % count number of lysine primary NH2s
> 
> Can you help to resolve this?

Sure thing. Would you mind sharing your crystal structure? Either PDB ID, or if you'd rather send me your structure via email ([hector.sanchez-moran@colorado.edu](mailto:hector.sanchez-moran@colorado.edu)) that would work too.

**Comment by Surabhi-CSB** [comment]
Hi Hector,

Thank you for the quick response. The protein I am working upon is basically modeled and is in the process of getting published. Hence, I am not allowed to share the PDB file. I am trying to use hi-patch to characterize its hydrophobic and hydrophilic surface area.

Is there another way you can help me resolve this error?
